### ISSUE TITLE
REG-338 Can't find new created applications

### ISSUE THREAD

**Issue by jeanouii** [tomitribe/tribestream-api-registry#144]
When creating a new application, we should be able to find it using the search screen. At the moment, it does not seem that the new application gets indexed.

**Comment by jeanouii** [comment]
See animated gif

![github-registry-144](https://cloud.githubusercontent.com/assets/1233474/19678271/50ffb566-9a9d-11e6-8d18-605a577bf7f1.gif)

**Comment by tbookless** [comment]
fixed in 0.5.4
