### ISSUE TITLE
History table must be refreshed on "save"

### ISSUE THREAD

**Issue by jeanouii** [tomitribe/tribestream-api-registry#146]
The history table at the bottom of the page does not seem to automatically refresh after saving the document. 

To reproduce, open an endpoint page. It has the revision table at the bottom.
Then, do a change and press "save".

You won't be seing any change in the revision table at the bottom until you reload the page.

**Comment by robertpanzer** [comment]
Strange, thought I fixed it here: https://github.com/tomitribe/tribestream-api-registry/commit/635fc954f9998aad3014c65c32ce6b84733b26b2#diff-e49a9c14b7077366ebffeb6b5c367bdfR116

**Comment by jeanouii** [comment]
Thanks @robertpanzer 
Might be the case. Lemme try it on a fresh master and I'll close if fixed already.

**Comment by jeanouii** [comment]
Fixed on master.
Thanks again @robertpanzer 
Something was wrong on my branch.

Closing.
