### ISSUE TITLE
REG-362 Bad user experience with create application page

### ISSUE THREAD

**Issue by jeanouii** [tomitribe/tribestream-api-registry#148]
The navigation and user experience when creating an application is not ideal. See upcoming animated gif.

**Comment by jeanouii** [comment]
![github-registry-148](https://cloud.githubusercontent.com/assets/1233474/19678534/70529586-9a9e-11e6-99e2-baf14ea3e9ae.gif)

As the animated gif shows, when entering into the application field, it takes the full screen width and moves to the next line the version.

It appears to look weird from a user point of view.
Can we make that a bit better?

**Comment by smittymac** [comment]
Agreed.  This felt odd to me as well.  Fields move about the screen as you tab.  Maybe required given you don't know size of application name?

**Comment by smittymac** [comment]
It is also hard to know what field you are in.  When tabbing out of the application name into the "next" field, you have to remember it was "Version" as the hint disappears as well as it moved position on the page.  At first I wasn't sure what field I was entering.

**Comment by smittymac** [comment]
And when I tab out of the Description field it seems to enable "code" mode instead of tabbing me out of the field like the others.  This may just be education for me that this is default "markup" language behavior for a text block field of some kind.  But felt odd for the newby.

**Comment by jeanouii** [comment]
Totally agree with all that. We need to fix that.

**Comment by tbookless** [comment]
fixed in 0.5.3
