### ISSUE TITLE
REG-344 Application description field should take the full width

### ISSUE THREAD

**Issue by jeanouii** [tomitribe/tribestream-api-registry#150]
When creating a new application for instance, there is no description.
The field is so small that you have to try to find it with your mouse on the page.

The field as in the endpoint page should take the full width.
![image](https://cloud.githubusercontent.com/assets/1233474/19678694/120d3d2c-9a9f-11e6-95ef-6e44c010b397.png)

**Comment by tbookless** [comment]
in release 0.5.2
