### ISSUE TITLE
Description hint missing on "Create Application"

### ISSUE THREAD

**Issue by smittymac** [tomitribe/tribestream-api-registry#153]
When creating an application you can see faded "Application Name" and "Version" fields but there is a hidden field beneath that might be description that has no hint.

This is found using Chrome Version 54.0.2840.71 (64-bit) on a Macbook Pro.

**Comment by smittymac** [comment]
Sorry, may be a duplicate for #147.

**Comment by jeanouii** [comment]
Hi @smittymac 
Thanks for reporting.

I think that is indeed a duplicated.
