### ISSUE TITLE
REG-318 "Create Endpoint" received "page not found" error

### ISSUE THREAD

**Issue by smittymac** [tomitribe/tribestream-api-registry#156]
When creating an application, after entering the application name, version and description (no way to save so not sure if I'm missing a step), clicking "+ Create Endpoint" sends me to a "page not found" page with the following URL:

https://<host>/registry/endpoint/

**Comment by jeanouii** [comment]
I found it weird as well and asked to rename the "create application" button "save".

So in short, for the version you are trying (0.5), when you are creating an application, after filling name, version and description, you can click "Create application" to save it.

I'll leave this ticket opened but I think it is fixed on master.
I also request to hide the "Create endpoint" button until the new application has been saved.

**Comment by smittymac** [comment]
Thank you, these are good adjustments.

**Comment by tbookless** [comment]
Fixed in 0.5.2
