### ISSUE TITLE
REG-317 - Warning dialog boxes in application for connection issues when there are no internet issues

### ISSUE THREAD

**Issue by smittymac** [tomitribe/tribestream-api-registry#158]
When trying to create an application, after clicking the button to save the details, two dialog Warning boxes open in the bottom right corner of the page.

One says the following:  "There are something wrong with your connection."

The second is empty (just says "Warning").

I seem to get this on many pages now.  No other internet related applications are having issues at this time (including this gethub :)  ).

![image](https://cloud.githubusercontent.com/assets/4693581/19682903/93e5bc10-9a64-11e6-8783-c57f1a149bdb.png)

**Comment by tveronezi** [comment]
thanks for reporting @smittymac . I will first fix that grammar issue - sorry for hurting your eyes with that. :) 

Can you check the browser console to see if there is any other message in there too?

**Comment by tbookless** [comment]
This is fixed and in review for the next update

**Comment by tbookless** [comment]
The grammar of the error has been fixed, and the save functionality has been reworked in 0.5.2
