### ISSUE TITLE
REG-339 Application Description Missing Label

### ISSUE THREAD

**Issue by JanetWongSBUX** [tomitribe/tribestream-api-registry#166]
In order for user to easily location the input box for the Application Description, please add a grey 'Description' inside the box so it shows up and/or put a label 'Description' on top of it so user can easily navigate to the input box without fishing around w/ the cursor.  One can easily get to it be tabbing from box to box but some folks may not use the tab key. 
![screen shot 2016-10-24 at 4 13 05 pm](https://cloud.githubusercontent.com/assets/23061594/19699882/e46f95ee-9aa9-11e6-90ba-ba839a944524.png)

**Comment by tbookless** [comment]
fixed in 1.5.2
