### ISSUE TITLE
REG-350 Creating an endpoint with a Method but an empty Path leads non-editable endpoint

### ISSUE THREAD

**Issue by martyhough** [tomitribe/tribestream-api-registry#170]
1. Create and Endpoint
2. Fill in the Method but leave the Path field Blank
3. Click Save.
4. Navigate back to the Application Page or Home Page
5. Click on the endpoint you just created that only shows the Method

Land on a "page not found" error making the endpoint no longer editable in the UI.

**Comment by tbookless** [comment]
Fixed in 0.5.2

**Comment by martyhough** [comment]
Not yet fixed in the version deployed yesterday but I believe that was 0.5.1.

Will check again after next deployment.
