### ISSUE TITLE
REG-347 rate limit isn't saved

### ISSUE THREAD

**Issue by JanetWongSBUX** [tomitribe/tribestream-api-registry#172]
i can't figure out how to save the rate limit.  first i key in a value, then keyed in a value in a drop down box with no label.  at once point i saw a drop down appears to be unit of measure - hours, days.  since it is an empty box, i keyed in hours.  but tabbing or entering doesn't save that value.  and the whole row isn't saved, including the numeric value i typed in before the unit of measure box.

**Comment by tbookless** [comment]
This does actually work, but poorly and is not very usable. I put in an enhancement to help.

**Comment by tbookless** [comment]
fixed in 0.5.4
