### ISSUE TITLE
REG-349 "API Versions", "Request Formats", and "Response Formats" will not save anything that is typed in.

### ISSUE THREAD

**Issue by martyhough** [tomitribe/tribestream-api-registry#174]
1. Create Endpoint
2. Type "1.01" in API Versions and select the checkmark - Note will not display until you navigate back
3. Type "application/bubba" in Request Formats and select the checkmark - Note will not display until you navigate back
4. Type "application/gump" in the Response Formats and select the checkmark - Note will not display until you navigate back
5. Click Save
6. Navigate Home and then select the endpoint you just edited

Note that none of these values were saved

**Comment by tbookless** [comment]
Workaround - press enter to save the entry.

The text entry should also be saved if the user clicks outside of the field or clicks the checkmark. I have added a ticket for that.

**Comment by tbookless** [comment]
fixed in 0.5.2
