### ISSUE TITLE
Page Not Found when creating EndPoint from within Application

### ISSUE THREAD

**Issue by mphillip** [tomitribe/tribestream-api-registry#187]
Steps to recreate:
1. Login
2. Click Create Application
3. Create Training Application, version 1.0
4. Click Create EndPoint
5. get Page Not Found Error

<img width="595" alt="screen shot 2016-10-28 at 12 37 28 pm" src="https://cloud.githubusercontent.com/assets/12173978/19819880/83e0fe66-9d0b-11e6-9049-b2169f4da1dc.png">

**Comment by mphillip** [comment]
Reading through the other issues, it appears maybe i need to create an endpoint before an application...but then on the homepage why does Create Application come before Create Endpoint?

**Comment by tbookless** [comment]
You do need to create an application first. We have an issue open to make that clearer.

**Comment by mphillip** [comment]
Also I cannot get it to create an application - there does not appear to be a save button for me, but I thought there would be since there is now a History section? Typing in and then just navigating away does not appear to do it.

**Comment by mphillip** [comment]
Nevermind - i got it now - but glad you are making it clearer.

**Comment by mphillip** [comment]
Maybe I should not have a Create Endpoint on the Create Application page, until the Application has been saved at least once.

**Comment by tbookless** [comment]
The new version fixes the save issue which will make that clearer. Sorry for the confusion.
