### ISSUE TITLE
REG-367 Home page - number of entries listed mismatch

### ISSUE THREAD

**Issue by mphillip** [tomitribe/tribestream-api-registry#189]
[homepage.pdf](https://github.com/tomitribe/tribestream-api-registry/files/559286/homepage.pdf)

Seems like the numbers listed are confusing and a mismatch - and there are no pagination buttons at the bottom if I should be able to see more Applications or Endpoints on a subsequent page.

**Comment by tbookless** [comment]
Fixed in 0.5.3
