### ISSUE TITLE
REG-392 Would like type-ahead feature to be case insensitive

### ISSUE THREAD

**Issue by mphillip** [tomitribe/tribestream-api-registry#191]
Example: In the status field of an endpoint I type "D" I get DRAFT in the autosuggest field. But if I type "d" I don't get the hint. I think I should get the hint regardless of case. As a new user that might give me the hint that I should be use all caps for this field.

**Comment by mphillip** [comment]
adding on some are upper case by default "GET" "POST" etc, and some lower "application/json", etc.

**Comment by tbookless** [comment]
fixed in 0.5.4
