### ISSUE TITLE
See all possible values in type ahead fields

### ISSUE THREAD

**Issue by mphillip** [tomitribe/tribestream-api-registry#192]
As a new API designer, I might not even know what all the possible things I could type in a field when there is type ahead added to it. For instance Authentication method - I found wondering should I be typing in JWT, Signature, or HTTP Signature, and had to try the first letter of each in upper and lower case to find one that would work. Maybe somehow an option to see what all the existing options are when the field takes the focus?

**Comment by tbookless** [comment]
There was a bug with the UI control so now, if you click in the field, you should see the whole list. If we need to edit a particular list, we can certainly do that, too.
