### ISSUE TITLE
Cannot create an application or an endpoint on IE- none of the fields are editable on IE

### ISSUE THREAD

**Issue by sbuxjava** [tomitribe/tribestream-api-registry#218]
None of the UI fields for IE are editable on "create endpoint" page.  They work fine on chrome.

**Comment by sbuxjava** [comment]
None of the UI fields are editable on "create application" page too on IE.

**Comment by tbookless** [comment]
What version of Internet Explorer and Windows are you using?

**Comment by sbuxjava** [comment]
internet Explorer version 11

**Comment by tbookless** [comment]
Fixed in 0.5.4

**Comment by tbookless** [comment]
IE 11 support needs more work

**Comment by tbookless** [comment]
fixed in 0.5.7

**Comment by tbookless** [comment]
IE 11 compatibility is still not where we would like it to be. Re-opening.

**Comment by tbookless** [comment]
fixed in 0.5.8
