### ISSUE TITLE
REG-384 Create endpoint -> description -> create numbered bulleted list incorrect

### ISSUE THREAD

**Issue by sbuxjava** [tomitribe/tribestream-api-registry#219]
All the bullets are numbered the same. If I have 3 line items they are all 1,1,1 instead of 1,2,3

**Comment by tbookless** [comment]
Would it be possible for you to provide some repro steps for this bug? Not sure what list you mean. Thanks.

**Comment by sbuxjava** [comment]
For the description field there is a text editor which has an option for numbered bulleted list. That is broken. Create text on 5 lines and highlight the text and hit this button for bulleted list. It will show every line item numbered as 1.

**Comment by tbookless** [comment]
This appears to be a bug with the Markdown control. We will file a bug fix with the the team that makes that open source control.

**Comment by tbookless** [comment]
fixed in 0.5.4
