### ISSUE TITLE
REG-383 create endpoint-> description -> markdownguide not working (question mark icon)

### ISSUE THREAD

**Issue by sbuxjava** [tomitribe/tribestream-api-registry#222]
1. click create endpoint
2. enter text in description
3. click '?' icon for markdown guide
4. this brings up the popup for markdown guide

there is no way to 'X' out of this screen and go back to "create endpoint" screen. The only way I can get out is by hitting the browser back button and loosing all the content I typed

**Comment by tbookless** [comment]
I will enter a bug for this. A workaround is to use the escape key to close the window.

**Comment by tbookless** [comment]
fixed in 0.5.4
