### ISSUE TITLE
REG-392 create endpoint-> status field case sensitivity issue

### ISSUE THREAD

**Issue by sbuxjava** [tomitribe/tribestream-api-registry#223]
1. click create endpoint
2.  go to status attribute and type "confidential". Do not save the endpoint

expected: the status should pick CONFIDENTIAL as the status option
actual: no matches and it is blank

interesting work around:
1. instead of typing select "CONFIDENTIAL" from the dropdown
2. now clear the text
3. Type "confidential" all lower case and the system seems to ignore the case sensitivity here and shows CONFIDENTIAL

**Comment by tbookless** [comment]
fixed in 0.5.4
