### ISSUE TITLE
IE11

### ISSUE THREAD

**Issue by tpturner2** [tomitribe/tribestream-api-registry#230]
When accessing in IE11 could not enter data in Create Application, Application Name or Version did not accept input. Did not experience the same thing in Chrome, able to input.

**Comment by tbookless** [comment]
Fixed in 0.5.4

**Comment by tbookless** [comment]
IE 11 support still needs work

**Comment by tbookless** [comment]
fixed in 0.5.7

**Comment by tbookless** [comment]
IE 11 compatibility is still not where we would like it to be. Re-opening.

**Comment by tbookless** [comment]
fixed in 0.5.8
