### ISSUE TITLE
numbered list  in the text editors incosistent

### ISSUE THREAD

**Issue by sbuxjava** [tomitribe/tribestream-api-registry#236]
1. click create endpoint
2. create text on multiple lines on a any filed with text editor for example description or request headers or response parameters
3. highlight the test
4. click the icon for numbering the bullet points

actual:
it numbers them all as 1. now click outside the text editor and it automatically changes the numbering to sequenced numbering as 1,2,3 etc

expected:
it should be sequentially numbered on the first go when the option to create numbering is clicked

**Comment by tbookless** [comment]
Appears to be a duplicate of #219
