### ISSUE TITLE
REG-387 Loading the homepage gives bad error request

### ISSUE THREAD

**Issue by sbuxjava** [tomitribe/tribestream-api-registry#244]
go to https://starbucks.tomitribe.com/registry/
we get "bad request " popup on chrome

**Comment by tbookless** [comment]
I believe that this is probably caused by an expired authorization token. We should be sending you back to the login page.

**Comment by tbookless** [comment]
fixed in 0.5.4

**Comment by tbookless** [comment]
This is a new issue that has to do with the Elastic Search Index being empty on a brand new install. We have another Jira open to address this.

**Comment by tbookless** [comment]
fixed in 0.5.8
