### ISSUE TITLE
"save left pane as endpoint" button does nothing

### ISSUE THREAD

**Issue by sbuxjava** [tomitribe/tribestream-api-registry#245]
1. select an application that has several lines saved under History section
2. Make a selection of a couple of line items under history and hit 'show difference'
3. click 'left pane as endpoint'. 

nothing seems to happen as i do not see an endpoint saved

**Comment by tbookless** [comment]
There are tiny arrows in the gray panel that separates the versions. You have to click on an arrow to accept a change. This lets the user pick one change at a time. The history section may get completely changed in the next version.
