### ISSUE TITLE
loading the home page still gives bad error pop up

### ISSUE THREAD

**Issue by sbuxjava** [tomitribe/tribestream-api-registry#293]
1. load home page on chrome https://starbucks.tomitribe.com/registry/
2. user gets pop up error that says "warning bad request"
The following bug was opened for the same reason and it was closed as fixed. I could not find a way to reopen the same bug so filing another one. Please comment if you know how to reopen a closed bug
https://github.com/tomitribe/tribestream-api-registry/issues/244

**Comment by tbookless** [comment]
Closing as duplicate. Re-opened 244.
