### ISSUE TITLE
endpoint version can accept any values including special characters

### ISSUE THREAD

**Issue by sbuxjava** [tomitribe/tribestream-api-registry#299]
1. create endpoint
2. enter name and description
3. go to endpoint version under resource information section and enter the following text
awilsifalksfalkfj!!#$!@$ and hit save

expect: some sort of error message
actual: it lets you save the endpoint

**Comment by tbookless** [comment]
The Endpoint Version is a text field for use by the API Designer. The tool does not apply any business rules for validation as this may vary per user and organization.
